function [Sreal,Simag] = compute_gremwi_signal(S0MW,S0IW,S0EW,r2sMW,r2sIW,r2sEW,freqMW,freqIW,freqEW,freqBKG,pini,decayEW,ff,TE,B0,gyro)

Sreal = (   S0MW .* exp(-TE .* r2sMW) .* cos(TE .* 2.*pi.*(freqMW+freqBKG).*B0.*gyro + pini) + ...
                            S0IW .* exp(-TE .* r2sIW) .* cos(TE .* 2.*pi.*(freqIW+freqBKG).*B0.*gyro + pini) + ...
                            S0EW .* exp(-TE .* r2sEW) .* cos(TE .* 2.*pi.*(freqEW+freqBKG).*B0.*gyro + pini) .* exp(-decayEW) ).*ff;

Simag = (   S0MW .* exp(-TE .* r2sMW) .* sin(TE .* 2.*pi.*(freqMW+freqBKG).*B0.*gyro + pini) + ...
                S0IW .* exp(-TE .* r2sIW) .* sin(TE .* 2.*pi.*(freqIW+freqBKG).*B0.*gyro + pini) + ...
                S0EW .* exp(-TE .* r2sEW) .* sin(TE .* 2.*pi.*(freqEW+freqBKG).*B0.*gyro + pini) .* exp(-decayEW) ).*ff;

end